### ISSUE TITLE
Portability of the library and json_auto_t type

### ISSUE THREAD

**Issue by osadalakmal** [latchset/jose#48]
in 803f0b425dce8b8ae1ebd822780b9f88749819c5 there was a dependency on a gcc specific cleanup feature that was introduced. This seems to have broken an otherwise portable C library.
But moreover akheron/jansson library which introduced this `json_auto_t` type did so within a ifdef check for GCC where as in this library it wasnt. Can we please introduce preprocessor guards to stop this feature from breaking the portability of the library?

**Comment by hkleynhans** [comment]
Related to: https://github.com/latchset/jose/issues/44

**Comment by osadalakmal** [comment]
Right, while it is true that Solris Studio compiler might support cleanup attribute plenty of others do not. Which is why I think jansson library wraps the use of it inside an ifdef block.

**Comment by npmccallum** [comment]
I'm the author of the json_auto_t feature in jansson. The cleanup attribute is supported by GCC, Clang and Sun Studio. It is also supported by MSVC through the Clang frontend. That is *very* portable.

This feature provides developers with a lot of benefit and ripping it out means we can't use it internally, which adds a lot of work for us.

Why can't you just use one of the above options?

**Comment by osadalakmal** [comment]
We do have to support AIX where even in the latest version of the compiler (XLC) it is not supported - http://www-01.ibm.com/support/docview.wss?uid=swg27046906&aid=9

**Comment by npmccallum** [comment]
Both GCC and Clang are available on AIX - even on old releases. 13+ years ago, when I was employed as an AIX developer, we had already given up on XLC since it couldn't keep pace with GCC. That has only worsened since Clang.

I'm not inclined to make the cleanup attribute optional since it save us a lot of work and it save you a lot of bugs.

**Comment by tiran** [comment]
As co-maintainer of jose, I agree with @npmccallum. In order to remove auto_t support, we'd have to refactor large amounts of code and replace auto_t with explicit error handling or goto-based cleanup. It would take some effort and introduce a new source of bugs.

In the past I have spent a considerable amount of time to fix compiler, architecture and CPU-related bugs in CPython, e.g. porting and keeping CPython working on SPARC machines with XLC compiler. It started as a hobbyist project, but was no fun in the end. I'd rather not spend my free time on XLC again.

**Comment by simo5** [comment]
Yep, it is time to move on, obsolete compilers like XLC should be let to rest in peace, and developers should really move to use modern compilers.
I am for closing this bug as a WONTFIX

**Comment by npmccallum** [comment]
WONTFIX
