### ISSUE TITLE
Changing ephemeral key type for JWEs

### ISSUE THREAD

**Issue by LiraNuna** [latchset/jose#56]
Is there a way to choose what encryption scheme is used for the CEK of a JWE? I noticed it always defaults to AES-CBC and I can't find any option or way (by glancing at the code) to use, say, AES-GCM or direct mode.

**Comment by npmccallum** [comment]
Yes. Set the `alg` header parameter in the input template.

**Comment by npmccallum** [comment]
https://tools.ietf.org/html/rfc7516#page-12

**Comment by LiraNuna** [comment]
```
$ echo hi | jose jwe enc -i '{"enc": "AGCM256"}' -I - -k key.jwk -c -o - | awk '{split($0,a,"."); print a[1]}' | jose b64 dec -i -
{"alg":"RSA-OAEP","enc":"A128CBC-HS256"}
```

Can you elaborate on how to do that? using `--help` doesn't show anything in specific

**Comment by npmccallum** [comment]
You are close:

```
$ echo hi \
  | jose jwe enc -i '{"protected":{"enc":"A256GCM"}}' -I- -k key.jwk -o- \
  | jose fmt -j- -g protected -y -o-
{"enc":"A256GCM"}
```

1. You don't need to use `awk` to parse the output. You can use the `jose fmt` command instead.
2. You need to set the `enc` parameter in the appropriate header location.

We give a similar example (using compression instead of choosing the encryption algorithm) in the man page `jose-jwe-enc`. See the examples section.
